version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - "perxhealth/engineering-managers"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    reviewers:
      - "perxhealth/engineering-managers"
