name: '"Static Deploy" for GitHub Actions'
description: Deploy static assets to an S3 bucket and invalidate its Cloudfront distribution
branding:
  icon: share
  color: blue
inputs:
  from:
    description: Path on local disk containing files to deploy
    required: true
  to:
    description: Fully qualified S3 bucket name and path, e.g. s3://bucket/path/to/deploy
    required: true
  cloudfront-distribution-id:
    description: Nominate the Cloudfront Distribution which serves assets from the bucket
    required: true
runs:
  using: node16
  main: dist/index.js
